version: '2'
mpp-vars:
  name: composefs
  image_size: '8589934592'
  arch: x86_64
  releasever: 37
  baseurl: http://download.fedoraproject.org/pub/fedora/linux/
  repos:
    - id: fedora
      baseurl: $baseurl/releases/$releasever/Everything/$arch/os/
    - id: fedora-updates
      baseurl: $baseurl/updates/$releasever/Everything/$arch/
  module_id: f$releasever
  root_password: $6$xoLqEUz0cGGJRx01$H3H/bFm0myJPULNMtbSsOFd/2BnHqHkMD92Sfxd.EKM9hXTWSmELG8cf205l6dktomuTcgKGGtGDgtvHVXSWU.
  guest_password: $6$xoLqEUz0cGGJRx01$H3H/bFm0myJPULNMtbSsOFd/2BnHqHkMD92Sfxd.EKM9hXTWSmELG8cf205l6dktomuTcgKGGtGDgtvHVXSWU.
  root_ssh_key: ""
  guest_uid: 1000
  guest_gid: 1000
  gpg_key:  "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmQINBF1RVqsBEADWMBqYv/G1r4PwyiPQCfg5fXFGXV1FCZ32qMi9gLUTv1CX7rYy\nH4Inj93oic+lt1kQ0kQCkINOwQczOkm6XDkEekmMrHknJpFLwrTK4AS28bYF2RjL\nM+QJ/dGXDMPYsP0tkLvoxaHr9WTRq89A+AmONcUAQIMJg3JxXAAafBi2UszUUEPI\nU35MyufFt2ePd1k/6hVAO8S2VT72TxXSY7Ha4X2J0pGzbqQ6Dq3AVzogsnoIi09A\n7fYutYZPVVAEGRUqavl0th8LyuZShASZ38CdAHBMvWV4bVZghd/wDV5ev3LXUE0o\nitLAqNSeiDJ3grKWN6v0qdU0l3Ya60sugABd3xaE+ROe8kDCy3WmAaO51Q880ZA2\niXOTJFObqkBTP9j9+ZeQ+KNE8SBoiH1EybKtBU8HmygZvu8ZC1TKUyL5gwGUJt8v\nergy5Bw3Q7av520sNGD3cIWr4fBAVYwdBoZT8RcsnU1PP67NmOGFcwSFJ/LpiOMC\npZ1IBvjOC7KyKEZY2/63kjW73mB7OHOd18BHtGVkA3QAdVlcSule/z68VOAy6bih\nE6mdxP28D4INsts8w6yr4G+3aEIN8u0qRQq66Ri5mOXTyle+ONudtfGg3U9lgicg\nz6oVk17RT0jV9uL6K41sGZ1sH/6yTXQKagdAYr3w1ix2L46JgzC+/+6SSwARAQAB\ntDFGZWRvcmEgKDMyKSA8ZmVkb3JhLTMyLXByaW1hcnlAZmVkb3JhcHJvamVjdC5v\ncmc+iQI4BBMBAgAiBQJdUVarAhsPBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAK\nCRBsEwJtEslE0LdAD/wKdAMtfzr7O2y06/sOPnrb3D39Y2DXbB8y0iEmRdBL29Bq\n5btxwmAka7JZRJVFxPsOVqZ6KARjS0/oCBmJc0jCRANFCtM4UjVHTSsxrJfuPkel\nvrlNE9tcR6OCRpuj/PZgUa39iifF/FTUfDgh4Q91xiQoLqfBxOJzravQHoK9VzrM\nNTOu6J6l4zeGzY/ocj6DpT+5fdUO/3HgGFNiNYPC6GVzeiA3AAVR0sCyGENuqqdg\nwUxV3BIht05M5Wcdvxg1U9x5I3yjkLQw+idvX4pevTiCh9/0u+4g80cT/21Cxsdx\n7+DVHaewXbF87QQIcOAing0S5QE67r2uPVxmWy/56TKUqDoyP8SNsV62lT2jutsj\nLevNxUky011g5w3bc61UeaeKrrurFdRs+RwBVkXmtqm/i6g0ZTWZyWGO6gJd+HWA\nqY1NYiq4+cMvNLatmA2sOoCsRNmE9q6jM/ESVgaH8hSp8GcLuzt9/r4PZZGl5CvU\neldOiD221u8rzuHmLs4dsgwJJ9pgLT0cUAsOpbMPI0JpGIPQ2SG6yK7LmO6HFOxb\nAkz7IGUt0gy1MzPTyBvnB+WgD1I+IQXXsJbhP5+d+d3mOnqsd6oDM/grKBzrhoUe\noNadc9uzjqKlOrmrdIR3Bz38SSiWlde5fu6xPqJdmGZRNjXtcyJlbSPVDIloxw==\n=QWRO\n-----END PGP PUBLIC KEY BLOCK-----\n"
  kernel_opts:
    - root=/dev/vda1
  build_rpms:
    - dnf
    - e2fsprogs
    - policycoreutils
    - python3-iniparse
    - python3
    - qemu-img
    - selinux-policy-targeted
    - systemd
    - tar
    - xz
  rootfs_uuid: '6264d520-3fb9-423f-8ab8-7a0a8e3d3563'
  fstab:
    - uuid:
        mpp-eval: rootfs_uuid
      vfs_type: ext4
      path: /
      freq: 1
      passno: 1
    - vfs_type: virtiofs
      path: /shared
      device: sharedfs
pipelines:
mpp-define-image:
  size: $image_size
  table:
    uuid: 'd209c89e-ea5e-4fbd-b161-b461cce297e1'
    label: gpt
    partitions:
    - id: root
      name: root
      type: '0FC63DAF-8483-4772-8E79-3D69D8477DE4'
      uuid: $rootfs_uuid
pipelines:
- name: build
  runner: org.osbuild.fedora37
  stages:
  - type: org.osbuild.rpm
    inputs:
      packages:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-depsolve:
          architecture: $arch
          module-platform-id: module_id
          baseurl: $baseurl
          repos:
            mpp-eval: repos
          packages:
            mpp-eval: build_rpms
    options:
      gpgkeys:
      - mpp-eval: gpg_key
      exclude:
        docs: true
  - type: org.osbuild.selinux
    options:
      file_contexts: etc/selinux/targeted/contexts/files/file_contexts
      labels:
        /usr/bin/cp: system_u:object_r:install_exec_t:s0
        /usr/bin/tar: system_u:object_r:install_exec_t:s0
- name: rootfs
  build: name:build
  stages:
  - type: org.osbuild.rpm
    options:
      gpgkeys:
        - mpp-eval: gpg_key
      disable_dracut: true
      exclude:
        docs: true
    inputs:
      packages:
        type: org.osbuild.files
        origin: org.osbuild.source
        mpp-depsolve:
          ignore-weak-deps: true
          architecture: $arch
          module-platform-id: module_id
          baseurl: $baseurl
          repos:
            mpp-eval: repos
          packages:
            - NetworkManager
            - e2fsprogs
            - glibc-langpack-en
            - hostname
            - passwd
            - rootfiles
            - selinux-policy-targeted
            - systemd-udev
            - bash-completion
            - dnf
            - openssh-clients
            - openssh-server
            - fsverity-utils
            - less
            - strace
            - vim
            - emacs-nox
            - sudo
  - type: org.osbuild.users
    options:
      users:
        root:
          password:
            mpp-eval: root_password
          key:
            mpp-eval: root_ssh_key
        guest:
          password:
            mpp-eval: guest_password
          gid:
            mpp-eval: guest_gid
          uid:
            mpp-eval: guest_uid
  - type: org.osbuild.sshd.config
    options:
      config:
        PermitRootLogin: true
  - type: org.osbuild.systemd
    options:
      enabled_services:
      - NetworkManager.service
      - sshd.service
  - type: org.osbuild.fstab
    options:
      filesystems:
        mpp-eval: fstab
  - type: org.osbuild.mkdir
    options:
      paths:
        - path: /shared
  # Unfortunately the ext4 stage doesn't allow enabling verity, so do at first boot
  - type: org.osbuild.first-boot
    options:
      commands:
        - "tune2fs -O verity /dev/vda1"
  - type: org.osbuild.selinux
    options:
      file_contexts: etc/selinux/targeted/contexts/files/file_contexts

- name: image
  build: name:build
  stages:
    - type: org.osbuild.truncate
      options:
        filename: disk.img
        size:
          mpp-eval: image.size
    - type: org.osbuild.sfdisk
      devices:
        device:
          type: org.osbuild.loopback
          options:
            filename: disk.img
      options:
        mpp-format-json: '{image.layout}'
    - type: org.osbuild.mkfs.ext4
      devices:
        device:
          type: org.osbuild.loopback
          options:
            filename: disk.img
            start:
              mpp-eval: image.layout['root'].start
            size:
              mpp-eval: image.layout['root'].size
      options:
        uuid:
          mpp-eval: rootfs_uuid
        label: root
    - type: org.osbuild.copy
      inputs:
        tree:
          type: org.osbuild.tree
          origin: org.osbuild.pipeline
          references:
          - name:rootfs
        build-tree:
          type: org.osbuild.tree
          origin: org.osbuild.pipeline
          references:
          - name:build
      options:
        paths:
          - from: input://tree/
            to: mount://root/
      devices:
        root:
          type: org.osbuild.loopback
          options:
            filename: disk.img
            start:
              mpp-eval: image.layout['root'].start
            size:
              mpp-eval: image.layout['root'].size
      mounts:
        - name: root
          type: org.osbuild.ext4
          source: root
          target: /

- name: qcow2
  build: name:build
  stages:
  - type: org.osbuild.qemu
    inputs:
      image:
        type: org.osbuild.files
        origin: org.osbuild.pipeline
        references:
          name:image:
            file: disk.img
    options:
      filename: disk.qcow2
      format:
        type: qcow2
        compat: '1.1'
